In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss, accuracy_score, f1_score, confusion_matrix, precision_score, recall_score, classification_report,roc_auc_score,roc_curve,RocCurveDisplay
import os
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt
os.chdir('/home/pgcp-ai/MachineLearning/Cases/Glass_Identification/')

In [2]:
glass = pd.read_csv('Glass.csv')
glass

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,building_windows_float_processed
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,building_windows_float_processed
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,building_windows_float_processed
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,building_windows_float_processed
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,building_windows_float_processed
...,...,...,...,...,...,...,...,...,...,...
209,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,headlamps
210,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,headlamps
211,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0,headlamps
212,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0,headlamps
213,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.0,headlamps

In [3]:
glass.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [4]:
le = LabelEncoder()
glass["Type"] = le.fit_transform(glass["Type"])

In [5]:
X, y = glass.drop("Type", axis = 1), glass["Type"]

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,stratify=y,random_state=26)

In [7]:
# ss = MinMaxScaler()
# X_train = ss.fit_transform(X_train)
# X_test = ss.transform(X_test)

In [8]:
nb = GaussianNB()
nb.fit(X_train,y_train) # Calculates all the apriori probabilities and 
y_pred_prob = nb.predict_proba(X_test) # Calculates the posterior probabilites

In [9]:
y_pred = nb.predict(X_test)
y_pred_labels = le.inverse_transform(y_pred)

In [10]:
print(log_loss(y_test, y_pred_prob))

5.325734873826645

In [11]:
print(accuracy_score(y_test, y_pred))

0.36923076923076925

In [12]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.71      0.24      0.36        21
           1       0.50      0.26      0.34        23
           2       0.33      0.25      0.29         4
           3       0.88      0.78      0.82         9
           4       0.75      1.00      0.86         3
           5       0.06      0.40      0.11         5

    accuracy                           0.37        65
   macro avg       0.54      0.49      0.46        65
weighted avg       0.59      0.37      0.42        65

In [13]:
os.chdir("/home/pgcp-ai/MachineLearning/Cases/Image_Segmentation/")

In [14]:
image = pd.read_csv("Image_Segmentation.csv")
image

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.000000,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.000000,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.000000,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.000000,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.000000,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,GRASS,36,243,9,0.111111,0.0,1.888889,1.851851,2.000000,0.711110,13.333333,9.888889,12.111111,18.000000,-10.333333,-3.666667,14.000000,18.000000,0.452229,2.368311
205,GRASS,186,218,9,0.000000,0.0,1.166667,0.744444,1.166667,0.655555,13.703704,10.666667,12.666667,17.777779,-9.111111,-3.111111,12.222222,17.777779,0.401347,2.382684
206,GRASS,197,236,9,0.000000,0.0,2.444444,6.829628,3.333333,7.599998,16.074074,13.111111,16.666668,18.444445,-8.888889,1.777778,7.111111,18.555555,0.292729,2.789800
207,GRASS,208,240,9,0.111111,0.0,1.055556,0.862963,2.444444,5.007407,14.148149,10.888889,13.000000,18.555555,-9.777778,-3.444444,13.222222,18.555555,0.421621,2.392487
208,GRASS,223,185,9,0.000000,0.0,0.500000,0.349603,2.388889,2.080776,12.962963,11.555555,9.777778,17.555555,-4.222222,-9.555555,13.777778,17.555555,0.445418,1.838850

In [15]:
image.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Class                 209 non-null    object
 1   region.centroid.col   209 non-null    int64
 2   region.centroid.row   209 non-null    int64
 3   region.pixel.count    209 non-null    int64
 4   short.line.density.5  209 non-null    float64
 5   short.line.density.2  209 non-null    float64
 6   vedge.mean            209 non-null    float64
 7   vegde.sd              209 non-null    float64
 8   hedge.mean            209 non-null    float64
 9   hedge.sd              209 non-null    float64
 10  intensity.mean        209 non-null    float64
 11  rawred.mean           209 non-null    float64
 12  rawblue.mean          209 non-null    float64
 13  rawgreen.mean         209 non-null    float64
 14  exred.mean            209 non-null    float64
 15  exblue.mean           209 non-null    float64
 16  exgreen.mean          209 non-null    float64
 17  value.mean            209 non-null    float64
 18  saturation.mean       209 non-null    float64
 19  hue-mean              209 non-null    float64
dtypes: float64(16), int64(3), object(1)
memory usage: 32.8+ KB

In [16]:
image.isna().sum()

Class                   0
region.centroid.col     0
region.centroid.row     0
region.pixel.count      0
short.line.density.5    0
short.line.density.2    0
vedge.mean              0
vegde.sd                0
hedge.mean              0
hedge.sd                0
intensity.mean          0
rawred.mean             0
rawblue.mean            0
rawgreen.mean           0
exred.mean              0
exblue.mean             0
exgreen.mean            0
value.mean              0
saturation.mean         0
hue-mean                0
dtype: int64

In [17]:
le = LabelEncoder()
image['Class'] = le.fit_transform(image['Class'])

In [18]:
X, y = image.drop("Class", axis = 1), image["Class"]

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,stratify=y,random_state=26)
nb = GaussianNB()
nb.fit(X_train,y_train) # Calculates all the apriori probabilities and 
y_pred_prob = nb.predict_proba(X_test) # Calculates the posterior probabilites

In [20]:
y_pred = nb.predict(X_test)
y_pred_labels = le.inverse_transform(y_pred)

In [21]:
print(log_loss(y_test, y_pred_prob))

4.4427332145824625

/home/pgcp-ai/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:2922: UserWarning: The y_pred values do not sum to one. Starting from 1.5 thiswill result in an error.
  warnings.warn(

In [22]:
print(accuracy_score(y_test, y_pred))

0.7619047619047619

In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.67      0.75         9
           1       0.88      0.78      0.82         9
           2       0.38      0.33      0.35         9
           3       1.00      1.00      1.00         9
           4       1.00      0.78      0.88         9
           5       1.00      1.00      1.00         9
           6       0.47      0.78      0.58         9

    accuracy                           0.76        63
   macro avg       0.80      0.76      0.77        63
weighted avg       0.80      0.76      0.77        63