In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.model_selection import train_test_split
import os
os.chdir('/home/pgcp-ai/MachineLearning/Datasets/')

In [2]:
boston = pd.read_csv("Boston.csv")

In [3]:
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [4]:
X, y = boston.drop('medv', axis = 1), boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26)

In [5]:
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
score = r2_score(y_test,y_pred)
score

0.5591480963256381

In [6]:
scores=[]
k=[1,2,3,4,5,6,7,8,9,10]
for i in k:
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    score = r2_score(y_test,y_pred)
    scores.append([i,score])
df_scores = pd.DataFrame(scores,columns=['k','scores'])
df_scores.sort_values('scores',ascending=False)

    k    scores
3   4  0.588671
2   3  0.559148
4   5  0.556344
5   6  0.515386
1   2  0.513579
6   7  0.496433
7   8  0.491477
8   9  0.479582
9  10  0.448195
0   1  0.293025

In [7]:
boston = pd.read_csv("Boston.csv")

In [8]:
X, y = boston.drop('medv', axis = 1), boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26)

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
minmax = MinMaxScaler()

In [11]:
X_train_scaled = minmax.fit_transform(X_train)
X_test_scaled = minmax.transform(X_test)

In [12]:
knn = KNeighborsRegressor(n_neighbors=4)
knn.fit(X_train_scaled,y_train)
y_pred = knn.predict(X_test_scaled)
score = r2_score(y_test,y_pred)
score

0.7117777226251241

In [13]:
scores=[]
k=[1,2,3,4,5,6,7,8,9,10]
for i in k:
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_scaled,y_train)
    y_pred = knn.predict(X_test_scaled)
    score = r2_score(y_test,y_pred)
    scores.append([i,score])
df_scores = pd.DataFrame(scores,columns=['k','scores'])
df_scores.sort_values('scores',ascending=False)

    k    scores
2   3  0.713301
3   4  0.711778
4   5  0.704968
1   2  0.692504
5   6  0.677821
0   1  0.675963
6   7  0.655112
7   8  0.639558
8   9  0.633555
9  10  0.627269

In [14]:
boston = pd.read_csv("Boston.csv")

In [15]:
X, y = boston.drop('medv', axis = 1), boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
ss = StandardScaler()

In [18]:
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

In [19]:
scores=[]
k=[1,2,3,4,5,6,7,8,9,10]
for i in k:
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train_scaled,y_train)
    y_pred = knn.predict(X_test_scaled)
    score = r2_score(y_test,y_pred)
    scores.append([i,score])
df_scores = pd.DataFrame(scores,columns=['k','scores'])
df_scores.sort_values('scores',ascending=False)

    k    scores
4   5  0.720809
3   4  0.720349
1   2  0.720333
8   9  0.708297
5   6  0.705555
2   3  0.704720
7   8  0.701514
6   7  0.701001
9  10  0.698105
0   1  0.691733