In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve,roc_auc_score,RocCurveDisplay, log_loss
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import os
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')
os.chdir("/home/pgcp-ai/MachineLearning/Cases/Image_Segmentation/")

In [ ]:
image = pd.read_csv("Image_Segmentation.csv")
image

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.000000,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.000000,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.000000,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.000000,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.000000,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,GRASS,36,243,9,0.111111,0.0,1.888889,1.851851,2.000000,0.711110,13.333333,9.888889,12.111111,18.000000,-10.333333,-3.666667,14.000000,18.000000,0.452229,2.368311
205,GRASS,186,218,9,0.000000,0.0,1.166667,0.744444,1.166667,0.655555,13.703704,10.666667,12.666667,17.777779,-9.111111,-3.111111,12.222222,17.777779,0.401347,2.382684
206,GRASS,197,236,9,0.000000,0.0,2.444444,6.829628,3.333333,7.599998,16.074074,13.111111,16.666668,18.444445,-8.888889,1.777778,7.111111,18.555555,0.292729,2.789800
207,GRASS,208,240,9,0.111111,0.0,1.055556,0.862963,2.444444,5.007407,14.148149,10.888889,13.000000,18.555555,-9.777778,-3.444444,13.222222,18.555555,0.421621,2.392487
208,GRASS,223,185,9,0.000000,0.0,0.500000,0.349603,2.388889,2.080776,12.962963,11.555555,9.777778,17.555555,-4.222222,-9.555555,13.777778,17.555555,0.445418,1.838850

In [ ]:
image.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Class                 209 non-null    object
 1   region.centroid.col   209 non-null    int64
 2   region.centroid.row   209 non-null    int64
 3   region.pixel.count    209 non-null    int64
 4   short.line.density.5  209 non-null    float64
 5   short.line.density.2  209 non-null    float64
 6   vedge.mean            209 non-null    float64
 7   vegde.sd              209 non-null    float64
 8   hedge.mean            209 non-null    float64
 9   hedge.sd              209 non-null    float64
 10  intensity.mean        209 non-null    float64
 11  rawred.mean           209 non-null    float64
 12  rawblue.mean          209 non-null    float64
 13  rawgreen.mean         209 non-null    float64
 14  exred.mean            209 non-null    float64
 15  exblue.mean           209 non-null    float64
 16  exgreen.mean          209 non-null    float64
 17  value.mean            209 non-null    float64
 18  saturation.mean       209 non-null    float64
 19  hue-mean              209 non-null    float64
dtypes: float64(16), int64(3), object(1)
memory usage: 32.8+ KB

In [ ]:
image.isna().sum()

Class                   0
region.centroid.col     0
region.centroid.row     0
region.pixel.count      0
short.line.density.5    0
short.line.density.2    0
vedge.mean              0
vegde.sd                0
hedge.mean              0
hedge.sd                0
intensity.mean          0
rawred.mean             0
rawblue.mean            0
rawgreen.mean           0
exred.mean              0
exblue.mean             0
exgreen.mean            0
value.mean              0
saturation.mean         0
hue-mean                0
dtype: int64

In [ ]:
le = LabelEncoder()
image['Class'] = le.fit_transform(image['Class'])
X, y = image.drop('Class', axis = 1), image['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26, stratify = image['Class'])

In [ ]:
solvers=['lbfgs','newton-cg','newton-cholesky','sag','saga']
C = np.linspace(0.001, 10, 30)

scores = []
for i in solvers:
    for j in C:
        lr = LogisticRegression(solver=i, C = j)
        lr.fit(X_train, y_train)
        y_pred = lr.predict_proba(X_test)
        scores.append([i, j, log_loss(y_test, y_pred)])

In [ ]:
df_scores = pd.DataFrame(scores, columns = ['Solver', 'C', 'Log Loss Score'])

In [ ]:
df_scores.sort_values('Log Loss Score', ascending=True)

              Solver         C  Log Loss Score
30         newton-cg  0.001000        0.477194
60   newton-cholesky  0.001000        0.643561
118              sag  9.655207        0.796496
107              sag  5.862483        0.797846
112              sag  7.586448        0.798228
..               ...       ...             ...
13             lbfgs  4.483310        1.847779
26             lbfgs  8.965621        1.868138
17             lbfgs  5.862483        1.885943
18             lbfgs  6.207276        1.946807
27             lbfgs  9.310414        1.977704

[150 rows x 3 columns]

In [ ]:
tst_img = pd.read_csv("tst_img.csv")
bm = LogisticRegression(solver = "newton-cg", C = 0.001)
bm.fit(X, y)

LogisticRegression(C=0.001, solver='newton-cg')

In [ ]:
tst_img['predicted_class'] = le.inverse_transform(bm.predict(tst_img))

In [ ]:
tst_img

,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean,predicted_class
0,22,90,10,0,0,0.666668,0.044444,0.880000,0.562963,112.000000,105.888885,128.555560,106.000000,-22.777779,45.222220,-22.444445,128.555560,0.179697,-2.097815,SKY
1,210,200,9,0,0,1.300000,0.998145,1.611111,1.123816,49.481480,45.000000,60.666668,43.000000,-14.111111,35.000000,-19.444445,60.666668,0.290788,-1.987599,PATH
2,240,184,9,0,0,0.500000,0.077778,0.777778,0.785185,11.851851,9.777778,9.888889,15.888889,-5.000000,-5.888889,13.000000,15.888889,0.500000,2.128646,GRASS
3,130,191,9,0,0,1.000000,0.400000,1.500000,1.011111,7.333334,5.333334,5.000000,11.222222,-7.000000,-5.666666,11.666667,11.222222,0.535820,2.122422,GRASS