In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_score, recall_score, classification_report
import os
import warnings
warnings.filterwarnings('ignore')
os.chdir('/home/pgcp-ai/MachineLearning/Cases/Glass_Identification/')

In [2]:
glass = pd.read_csv("Glass.csv")
glass

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,building_windows_float_processed
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,building_windows_float_processed
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,building_windows_float_processed
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,building_windows_float_processed
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,building_windows_float_processed
...,...,...,...,...,...,...,...,...,...,...
209,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,headlamps
210,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,headlamps
211,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0,headlamps
212,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0,headlamps
213,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.0,headlamps

In [3]:
X, y = glass.drop('Type', axis = 1), glass['Type']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26,stratify=glass['Type'])

In [13]:
solvers=['lbfgs','newton-cg','newton-cholesky','sag','saga']
Cs = np.linspace(0.001,5,20)
scores = []
for s in solvers:
    for c in Cs:
        lr = LogisticRegression(solver=s,C=c)
        lr.fit(X_train,y_train)
        y_pred = lr.predict(X_test)
        scores.append([s,c,f1_score(y_test,y_pred,average='macro')])

In [16]:
df_scores = pd.DataFrame(scores,columns=['Solver','C','Score'])
df_scores.sort_values('Score',ascending=False)

             Solver         C     Score
11            lbfgs  2.895158  0.537121
18            lbfgs  4.736895  0.513396
16            lbfgs  4.210684  0.508634
19            lbfgs  5.000000  0.506542
59  newton-cholesky  5.000000  0.499464
..              ...       ...       ...
80             saga  0.001000  0.087121
60              sag  0.001000  0.087121
40  newton-cholesky  0.001000  0.087121
20        newton-cg  0.001000  0.087121
0             lbfgs  0.001000  0.087121

[100 rows x 3 columns]

In [17]:
bm = LogisticRegression(solver = 'lbfgs', C = 2.895158)
bm.fit(X, y)

LogisticRegression(C=2.895158)

In [18]:
glassTest = pd.read_csv('tst_Glass.csv')
glassTest

       RI    Na    Mg    Al     Si      K    Ca    Ba     Fe
0  1.5321  14.0  0.00  0.34  70.23  0.001   6.7  1.23  0.000
1  1.5212  15.0  3.00  1.23  75.90  0.100   7.0  0.00  0.440
2  1.5112  13.0  3.50  2.30  73.00  3.400  14.0  2.30  0.220
3  1.5000  12.4  1.23  3.22  74.22  4.500  10.0  3.10  0.100
4  1.5200  13.0  2.40  0.34  71.22  3.200   9.0  1.44  0.001
5  1.5100  16.0  2.70  4.00  70.00  2.000   6.0  2.90  0.890

In [19]:
glassTest['type_window'] = bm.predict(glassTest)
glassTest

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,type_window
0,1.5321,14.0,0.00,0.34,70.23,0.001,6.7,1.23,0.000,headlamps
1,1.5212,15.0,3.00,1.23,75.90,0.100,7.0,0.00,0.440,tableware
2,1.5112,13.0,3.50,2.30,73.00,3.400,14.0,2.30,0.220,building_windows_non_float_processed
3,1.5000,12.4,1.23,3.22,74.22,4.500,10.0,3.10,0.100,containers
4,1.5200,13.0,2.40,0.34,71.22,3.200,9.0,1.44,0.001,building_windows_non_float_processed
5,1.5100,16.0,2.70,4.00,70.00,2.000,6.0,2.90,0.890,headlamps

In [20]:
X.shape

(214, 9)

In [21]:
bm.intercept_

array([-0.011073  ,  0.02022624,  0.00774262, -0.00410173, -0.0209858 ,
        0.00819167])