In [17]:
from sentence_transformers import SentenceTransformer
from tqdm import tqdm
import pandas as pd
import numpy as np

In [3]:
model = SentenceTransformer("BAAI/bge-m3")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\PGCP-AI\AppData\Local\anaconda3\envs\surpsiseNew\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\PGCP-AI\.cache\huggingface\hub\models--BAAI--bge-m3. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [6]:
sentences = ["He batted well today in the cricket match",
             "Tomorrow will be Wednesday",
             "She played excellently yesterda with many goals.",
             "Today will be the event",
             "He performed well in that game"
            ]

In [9]:
embeddings = model.encode(["Tomorrow will be Wednesday"])
# embeddings.shape
embeddings

array([[-0.01675646,  0.00072814, -0.0189868 , ..., -0.0101895 ,
        -0.00574521,  0.01872203]], dtype=float32)

In [13]:
similarity = model.similarity(embeddings,embeddings)
similarity

tensor([[1.0000, 0.5229, 0.6803, 0.6316, 0.8413],
        [0.5229, 1.0000, 0.5195, 0.7772, 0.5083],
        [0.6803, 0.5195, 1.0000, 0.5255, 0.7251],
        [0.6316, 0.7772, 0.5255, 1.0000, 0.5554],
        [0.8413, 0.5083, 0.7251, 0.5554, 1.0000]])

In [14]:
import pandas as pd
import numpy as np
import os 
os.chdir('C:/Users/PGCP-AI/ML/MachineLearning/Cases_Rec_Sys/Netflix')

In [16]:
df = pd.read_csv('titles.csv')
df

             id                                      title   type  ... imdb_votes  tmdb_popularity tmdb_score
0      ts300399        Five Came Back: The Reference Films   SHOW  ...        NaN            0.600        NaN
1       tm84618                                Taxi Driver  MOVIE  ...   808582.0           40.965      8.179
2      tm154986                                Deliverance  MOVIE  ...   107673.0           10.010      7.300
3      tm127384            Monty Python and the Holy Grail  MOVIE  ...   534486.0           15.461      7.811
4      tm120801                            The Dirty Dozen  MOVIE  ...    72662.0           20.398      7.600
...         ...                                        ...    ...  ...        ...              ...        ...
5845  tm1014599                                  Fine Wine  MOVIE  ...       45.0            1.466        NaN
5846   tm898842                                C/O Kaadhal  MOVIE  ...      348.0              NaN        NaN
5847  tm1059008                                    Lokillo  MOVIE  ...       68.0           26.005      6.300
5848  tm1035612  Dad Stop Embarrassing Me - The Afterparty  MOVIE  ...        NaN            1.296     10.000
5849   ts271048         Mighty Little Bheem: Kite Festival   SHOW  ...       18.0            2.289     10.000

[5850 rows x 15 columns]

In [19]:
df_indian_movies = df[(df['production_countries'].str.contains('IN')) & (df['type'] == 'MOVIE') & (df['release_year'] >= 1980)]
df_indian_movies.shape

(570, 15)

In [20]:
all_desc = list(df_indian_movies['description'])
out_embs = []
for r in tqdm(all_desc):
    embd = model.encode(r)
    out_embs.append(embd)

out_embs = np.array(out_embs)
out_embs.shape

100%|████████████████████████████████████████████████████████████████████████████████| 570/570 [02:39<00:00,  3.56it/s]

(570, 1024)

In [22]:
query = "detective investigating a robbery"
quer1 = ""
qy_emb = model.encode([query])
sims = []

for e in tqdm(out_embs):
    sims.append(model.similarity(qy_emb, e).numpy()[0])
df_ind = df_indian_movies[['id', 'title', 'description', 'release_year']].copy()
df_ind['sims'] = np.array(sims)
df_ind.sort_values('sims', ascending = False)[:5]

100%|██████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 5059.48it/s]

            id            title                                        description  release_year      sims
2490  tm307774     Jagga Jasoos  A gifted teenage detective searches for his mi...          2017  0.652046
801    tm34142       Department  A police inspector recruits a suspended cop fo...          2012  0.632100
1520  tm233366             Te3n  A grandfather, police officer and a priest joi...          2016  0.623418
2864  tm374395  Vanjagar Ulagam  A woman is murdered and her neighbour is picke...          2018  0.622395
3498  tm857051         Forensic  A forensic analyst and an investigation office...          2020  0.618724

In [47]:
query = "An ordinary guy gains extraordinary superpowers after coming in contact with a kind alien"

qy_emb = model.encode([query])
sims = []

for e in tqdm(out_embs):
    sims.append(model.similarity(qy_emb, e).numpy()[0])
df_ind = df_indian_movies[['id', 'title', 'description', 'release_year']].copy()
df_ind['sims'] = np.array(sims)
df_ind.sort_values('sims', ascending = False)[:5]

100%|██████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 5088.48it/s]

             id                    title                                        description  release_year      sims
2413   tm417317  Bhavesh Joshi Superhero  A young man who stands for the right discovers...          2018  0.664046
512    tm103133  Karthik Calling Karthik  A much abused loner achieves success, and even...          2010  0.637810
5664  tm1067260           Tughlaq Durbar  A budding politician has devious plans to rise...          2021  0.604988
5052  tm1086874            Minnal Murali  A tailor gains special powers after being stru...          2021  0.597263
2528   tm372061      Sudani from Nigeria  When a soccer club manager brings one of his i...          2018  0.596345