In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import os
os.chdir('/home/pgcp-ai/MachineLearning/Datasets')

In [2]:
df = pd.read_csv('Housing.csv')
df

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [3]:
df=pd.get_dummies(df,dtype=int, drop_first = True)
df

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,42000.0,5850,3,1,2,1,1,0,1,0,0,0
1,38500.0,4000,2,1,1,0,1,0,0,0,0,0
2,49500.0,3060,3,1,1,0,1,0,0,0,0,0
3,60500.0,6650,3,1,2,0,1,1,0,0,0,0
4,61000.0,6360,2,1,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,0,1,1,0,0,1,0
542,94000.0,6000,3,2,4,0,1,0,0,0,1,0
543,103000.0,6000,3,2,4,1,1,1,0,0,1,0
544,105000.0,6000,3,2,2,1,1,1,0,0,1,0
545,105000.0,6000,3,1,2,1,1,0,0,0,1,0

In [4]:
df.dtypes

price           float64
lotsize           int64
bedrooms          int64
bathrms           int64
stories           int64
garagepl          int64
driveway_yes      int64
recroom_yes       int64
fullbase_yes      int64
gashw_yes         int64
airco_yes         int64
prefarea_yes      int64
dtype: object

In [5]:
df.isna().sum()

price           0
lotsize         0
bedrooms        0
bathrms         0
stories         0
garagepl        0
driveway_yes    0
recroom_yes     0
fullbase_yes    0
gashw_yes       0
airco_yes       0
prefarea_yes    0
dtype: int64

In [6]:
X = df.drop('price',axis=1)
y = df['price']

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [8]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [9]:
y_pred = model.predict(X_test)

In [10]:
test = pd.read_csv("tst_Housing.csv")
test
test = pd.get_dummies(test,dtype = int)
test

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_no,recroom_yes,fullbase_no,fullbase_yes,gashw_no,airco_no,prefarea_no
0,5600,3,1,2,1,1,1,0,0,1,1,1,1
1,4355,2,1,1,0,1,1,0,1,0,1,1,1
2,3412,3,1,1,0,1,1,0,1,0,1,1,1
3,6666,2,2,2,0,1,0,1,1,0,1,1,1

In [11]:
r2_score(y_test,y_pred)

0.6791781818067917

In [12]:
alpha_values = np.linspace(0.01, 10)
dict_alpha = dict()
for i in alpha_values:
    lasso = Lasso(alpha = i)
    lasso.fit(X_train, y_train)
    y_pred_lasso = lasso.predict(X_test)
    dict_alpha[i] = r2_score(y_test, y_pred_lasso)
    
lasso_df = pd.DataFrame(dict_alpha.items(), columns = ['Alpha', 'Score'])
lasso_df.sort_values('Score', ascending = False).iloc[0]

Alpha    0.010000
Score    0.679178
Name: 0, dtype: float64

In [13]:
alpha_values = np.linspace(0.01, 10)
dict_alpha = dict()
for i in alpha_values:
    ridge = Ridge(alpha = i)
    ridge.fit(X_train, y_train)
    y_pred_ridge = ridge.predict(X_test)
    dict_alpha[i] = r2_score(y_test, y_pred_ridge)
    
ridge_df = pd.DataFrame(dict_alpha.items(), columns = ['Alpha', 'Score'])
ridge_df.sort_values('Score', ascending = False).iloc[0]

Alpha    0.010000
Score    0.679171
Name: 0, dtype: float64

In [14]:
alpha_values = np.linspace(0.01, 10)
l1_ratio = np.linspace(0, 0.5)
scores=[]
dict_alpha = dict()
for i,j in zip(alpha_values,l1_ratio):
    ridge = ElasticNet(alpha = i,l1_ratio=j)
    ridge.fit(X_train, y_train)
    y_pred_ridge = ridge.predict(X_test)
    dict_alpha[i] = r2_score(y_test, y_pred_ridge)
#     scores.append([i,j, r2_score(y_test, y_pred_ElasticNet)])

ridge_df = pd.DataFrame(dict_alpha.items(), columns = ['Alpha', 'Score'])
ridge_df.sort_values('Score', ascending = False).iloc[0]

/home/pgcp-ai/.local/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.749e+10, tolerance: 2.726e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

Alpha    0.010000
Score    0.676053
Name: 0, dtype: float64

In [15]:
test = pd.read_csv("tst_Housing.csv")
test

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no

In [16]:
# test.rename(columns={'driveway':'driveway_yes','recroom':'recroom_yes','fullbase':'fullbase_yes','gashw':'gashw_yes','airco':'airco_yes','prefarea':'prefarea_yes'},inplace=True)

In [17]:
test

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no

In [18]:
dum_test = pd.get_dummies(test,dtype=int,drop_first=True)
dum_test

   lotsize  bedrooms  bathrms  stories  garagepl  recroom_yes  fullbase_yes
0     5600         3        1        2         1            0             1
1     4355         2        1        1         0            0             0
2     3412         3        1        1         0            0             0
3     6666         2        2        2         0            1             0

In [19]:
dum_test.columns

Index(['lotsize', 'bedrooms', 'bathrms', 'stories', 'garagepl', 'recroom_yes',
       'fullbase_yes'],
      dtype='object')

In [20]:
df.columns

Index(['price', 'lotsize', 'bedrooms', 'bathrms', 'stories', 'garagepl',
       'driveway_yes', 'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes',
       'prefarea_yes'],
      dtype='object')

### Creating columns that are missing in the test dataset

In [21]:
dum_test[['airco_yes','gashw_yes','prefarea_yes']] = False
dum_test['driveway_yes'] = True

In [22]:
dum_test

,lotsize,bedrooms,bathrms,stories,garagepl,recroom_yes,fullbase_yes,airco_yes,gashw_yes,prefarea_yes,driveway_yes
0,5600,3,1,2,1,0,1,False,False,False,True
1,4355,2,1,1,0,0,0,False,False,False,True
2,3412,3,1,1,0,0,0,False,False,False,True
3,6666,2,2,2,0,1,0,False,False,False,True

### Arranging the columns in similar way as the original training data

In [23]:
dum_test = dum_test[[ 'lotsize', 'bedrooms', 'bathrms', 'stories', 'garagepl',
       'driveway_yes', 'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes', 'prefarea_yes']]

In [24]:
model = LinearRegression()

In [25]:
model.fit(X,y)

LinearRegression()

In [26]:
y_pred_Inferencing = model.predict(dum_test)
y_pred_Inferencing

array([65151.39992985, 42650.08901117, 41137.92877603, 76249.38318098])