In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import os
from sklearn.compose import ColumnTransformer
os.chdir('/home/pgcp-ai/MachineLearning/Datasets')

In [2]:
tel = pd.read_csv("Telecom.csv")

In [3]:
ohe = OneHotEncoder(sparse_output = False, drop='first').set_output(transform='pandas')
ohe.fit_transform(tel)

     Gender_M  TT_gt_100_Y  Response_Y
0         0.0          1.0         0.0
1         1.0          0.0         0.0
2         1.0          0.0         0.0
3         0.0          1.0         1.0
4         0.0          0.0         0.0
..        ...          ...         ...
145       0.0          1.0         1.0
146       1.0          0.0         1.0
147       1.0          0.0         0.0
148       1.0          0.0         0.0
149       0.0          0.0         0.0

[150 rows x 3 columns]

In [4]:
housing = pd.read_csv('Housing.csv')

In [5]:
# ohe = OneHotEncoder(sparse_output = False, drop='first').set_output(transform='pandas')
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [6]:
housing.info()
list(housing.select_dtypes(include = 'object').columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     546 non-null    float64
 1   lotsize   546 non-null    int64
 2   bedrooms  546 non-null    int64
 3   bathrms   546 non-null    int64
 4   stories   546 non-null    int64
 5   driveway  546 non-null    object
 6   recroom   546 non-null    object
 7   fullbase  546 non-null    object
 8   gashw     546 non-null    object
 9   airco     546 non-null    object
 10  garagepl  546 non-null    int64
 11  prefarea  546 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 51.3+ KB

['driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'prefarea']

In [7]:
transformer = ColumnTransformer(transformers=[("OHE",ohe,['driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'prefarea'])], 
                               remainder = 'passthrough', verbose_feature_names_out = False).set_output(transform='pandas')
transformer.fit_transform(housing)

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,price,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,42000.0,5850,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,38500.0,4000,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,49500.0,3060,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,60500.0,6650,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,61000.0,6360,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,1.0,1.0,0.0,0.0,1.0,0.0,91500.0,4800,3,2,4,0
542,1.0,0.0,0.0,0.0,1.0,0.0,94000.0,6000,3,2,4,0
543,1.0,1.0,0.0,0.0,1.0,0.0,103000.0,6000,3,2,4,1
544,1.0,1.0,0.0,0.0,1.0,0.0,105000.0,6000,3,2,2,1
545,1.0,0.0,0.0,0.0,1.0,0.0,105000.0,6000,3,1,2,1

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
ss = StandardScaler()

In [12]:
transformer_1 = ColumnTransformer(transformers=[("OHE",ohe,list(housing.select_dtypes(include='object'))),("SS",ss,['lotsize','price'])
                                               ],
                                 remainder='passthrough',
                                 verbose_feature_names_out=False).set_output(transform='pandas')
housing = transformer_1.fit_transform(housing)

In [13]:
housing

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,lotsize,price,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,0.323028,-0.979136,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,-0.531013,-1.110329,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,-0.964958,-0.698008,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,0.692343,-0.285686,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.558466,-0.266944,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,1.0,1.0,0.0,0.0,1.0,0.0,-0.161698,0.876311,3,2,4,0
542,1.0,0.0,0.0,0.0,1.0,0.0,0.392275,0.970020,3,2,4,0
543,1.0,1.0,0.0,0.0,1.0,0.0,0.392275,1.307374,3,2,4,1
544,1.0,1.0,0.0,0.0,1.0,0.0,0.392275,1.382342,3,2,2,1
545,1.0,0.0,0.0,0.0,1.0,0.0,0.392275,1.382342,3,1,2,1

In [14]:
from sklearn.compose import make_column_selector

In [15]:
transformer2 = ColumnTransformer(transformers=[("OHE",ohe, make_column_selector(dtype_include=object) )], 
                               remainder = 'passthrough', verbose_feature_names_out = False).set_output(transform='pandas')
transformer2.fit_transform(housing)

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,lotsize,price,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,0.323028,-0.979136,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,-0.531013,-1.110329,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,-0.964958,-0.698008,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,0.692343,-0.285686,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.558466,-0.266944,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,1.0,1.0,0.0,0.0,1.0,0.0,-0.161698,0.876311,3,2,4,0
542,1.0,0.0,0.0,0.0,1.0,0.0,0.392275,0.970020,3,2,4,0
543,1.0,1.0,0.0,0.0,1.0,0.0,0.392275,1.307374,3,2,4,1
544,1.0,1.0,0.0,0.0,1.0,0.0,0.392275,1.382342,3,2,2,1
545,1.0,0.0,0.0,0.0,1.0,0.0,0.392275,1.382342,3,1,2,1