In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
import os
import warnings 
warnings.filterwarnings('ignore')
os.chdir("/home/pgcp-ai/MachineLearning/Datasets/")

In [2]:
fp_df = pd.read_csv("Faceplate.csv", index_col = 0)
fp_df = fp_df.astype(bool)
itemsets = apriori(fp_df, min_support = 0.2, use_colnames = True)
rules = association_rules(itemsets, metric = 'confidence', min_threshold = 0.6)
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
relv_rules = rules[rules['lift'] > 1]
relv_rules.sort_values('lift', ascending = False)

      antecedents   consequents  support  confidence      lift
9         (Green)  (White, Red)      0.2    1.000000  2.500000
3         (Green)         (Red)      0.2    1.000000  1.666667
7  (White, Green)         (Red)      0.2    1.000000  1.666667
5        (Orange)       (White)      0.2    1.000000  1.428571
6         (Green)       (White)      0.2    1.000000  1.428571
8    (Green, Red)       (White)      0.2    1.000000  1.428571
1          (Blue)         (Red)      0.4    0.666667  1.111111
2           (Red)        (Blue)      0.4    0.666667  1.111111

In [3]:
from ipywidgets import interact,widgets

In [4]:
cosmetics = pd.read_csv('Cosmetics.csv',index_col=0)
cosmetics

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
Trans.,,,,,,,,,,,,,,
1,0,1,1,1,1,0,1,1,1,0,0,0,0,1
2,0,0,1,0,1,0,1,1,0,0,1,1,0,0
3,0,1,0,0,1,1,1,1,1,1,1,1,1,0
4,0,0,1,1,1,0,1,0,0,0,1,0,0,1
5,0,1,0,0,1,0,1,1,1,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,0,0,0,0,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,1,1,0,0
998,0,1,1,1,1,0,0,1,0,0,1,0,1,1
999,1,1,0,0,1,0,0,0,1,1,0,0,1,1
1000,0,0,0,0,1,0,1,1,0,1,0,0,0,1

In [5]:
def cosmetic_fun(Min_Support,Min_Threshold):
    itemsets = apriori(cosmetics, min_support = Min_Support, use_colnames = True)
    rules = association_rules(itemsets, metric = 'confidence', min_threshold = Min_Threshold)
    rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
    relv_rules = rules[rules['lift'] > 1]
    if len(relv_rules) == 0:
        return f"No Relevant Rules Found!!"
    else:
        return relv_rules.sort_values('lift',ascending=False)

In [7]:
interact(cosmetic_fun, Min_Support = widgets.FloatSlider(min = 0.01, max = 1, step = 0.01, value = 0.3,description="Minimum Support: "),
         Min_Threshold = widgets.FloatSlider(min = 0.01, max = 1, step = 0.01, value = 0.3,description="Minimum Threshold: "))

Widget Javascript not detected.  It may not be installed or enabled properly.