In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error

In [2]:
df = pd.read_csv('/home/pgcp-ai/Datasets/Concrete_Data.csv')
df

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [3]:
X = df.drop('Strength',axis=1)
y = df['Strength']
X

      Cement  Blast    Fly  Water  Superplasticizer  Coarse   Fine  Age
0      540.0    0.0    0.0  162.0               2.5  1040.0  676.0   28
1      540.0    0.0    0.0  162.0               2.5  1055.0  676.0   28
2      332.5  142.5    0.0  228.0               0.0   932.0  594.0  270
3      332.5  142.5    0.0  228.0               0.0   932.0  594.0  365
4      198.6  132.4    0.0  192.0               0.0   978.4  825.5  360
...      ...    ...    ...    ...               ...     ...    ...  ...
1025   276.4  116.0   90.3  179.6               8.9   870.1  768.3   28
1026   322.2    0.0  115.6  196.0              10.4   817.9  813.4   28
1027   148.5  139.4  108.6  192.7               6.1   892.4  780.0   28
1028   159.1  186.7    0.0  175.6              11.3   989.6  788.9   28
1029   260.9  100.5   78.3  200.6               8.6   864.5  761.5   28

[1030 rows x 8 columns]

In [10]:
df.isna().sum()

Cement              0
Blast               0
Fly                 0
Water               0
Superplasticizer    0
Coarse              0
Fine                0
Age                 0
Strength            0
dtype: int64

### Degree 1

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [5]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [6]:
print(f"R2 Score: {r2_score(y_test,y_pred)}")

R2 Score: 0.61814647284644

### Degree 2

In [7]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform = 'pandas')
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size = 0.3, random_state = 26)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print("R2 = ", r2_score(y_test, y_pred))

R2 =  0.8116988468556121

### Degree 3

In [8]:
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform = 'pandas')
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size = 0.3, random_state = 26)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print("R2 = ", r2_score(y_test, y_pred))

R2 =  0.7840077966155438

### Degree 4

In [9]:
poly = PolynomialFeatures(degree=4, include_bias=False).set_output(transform = 'pandas')
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size = 0.3, random_state = 26)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print("R2 = ", r2_score(y_test, y_pred))

R2 =  -17.440113166299085

### Ridge

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26)

In [24]:
alpha_values = np.linspace(0.001, 10,100)
dict_alpha = dict()
for i in alpha_values:
    ridge = Ridge(alpha = i)
    ridge.fit(X_train, y_train)
    y_pred_ridge = ridge.predict(X_test)
    dict_alpha[i] = r2_score(y_test, y_pred_ridge)
    
ridge_df = pd.DataFrame(dict_alpha.items(), columns = ['Alpha', 'Score'])
ridge_df.sort_values('Score', ascending = False)

     Alpha     Score
99  10.000  0.618152
98   9.899  0.618152
97   9.798  0.618152
96   9.697  0.618152
95   9.596  0.618152
..     ...       ...
4    0.405  0.618147
3    0.304  0.618147
2    0.203  0.618147
1    0.102  0.618147
0    0.001  0.618146

[100 rows x 2 columns]