In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import os
os.chdir('/home/pgcp-ai/MachineLearning/Datasets')

### Pizza Dataset

In [2]:
pizza = pd.read_csv("pizza.csv")
pizza

    Promote  Sales
0        23    554
1        56   1339
2        34    815
3        25    609
4        67   1600
5        82   2000
6        46   1000
7        14    300
8         6    150
9        47   1150
10       52   1200
11       88   2000
12       71   1750
13       78   2000
14       66   1500
15       44   1000
16       68   1600
17       90   2000
18       22    550

In [3]:
X = pizza[['Promote']]
y = pizza['Sales']

In [4]:
poly = PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)
X_poly

    Promote  Promote^2
0      23.0      529.0
1      56.0     3136.0
2      34.0     1156.0
3      25.0      625.0
4      67.0     4489.0
5      82.0     6724.0
6      46.0     2116.0
7      14.0      196.0
8       6.0       36.0
9      47.0     2209.0
10     52.0     2704.0
11     88.0     7744.0
12     71.0     5041.0
13     78.0     6084.0
14     66.0     4356.0
15     44.0     1936.0
16     68.0     4624.0
17     90.0     8100.0
18     22.0      484.0

In [5]:
lr = LinearRegression()
lr.fit(X_poly,y)

LinearRegression()

In [6]:
lr.coef_,lr.intercept_

(array([ 2.48006959e+01, -1.30947333e-02]), -18.274917416646076)

### Insure Auto

In [7]:
insure = pd.read_csv("Insure_auto.csv")
insure

  Branch  Home  Automobile  Operating_Cost
0    B01   400        1200          124000
1    B02   350         360           71000
2    B03   600         800          136000
3    B04   800        1800          219000
4    B05   900        1600          230000
5    B06   200        1000           75000
6    B07   120         900           56000
7    B08   340        1100          110000
8    B09   490         900          120000
9    B10   700         800          144000

In [8]:
X = insure[['Home','Automobile']]
y = insure['Operating_Cost']
poly = PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly_deg_2 = poly.fit_transform(X)
X_poly_deg_2

    Home  Automobile    Home^2  Home Automobile  Automobile^2
0  400.0      1200.0  160000.0         480000.0     1440000.0
1  350.0       360.0  122500.0         126000.0      129600.0
2  600.0       800.0  360000.0         480000.0      640000.0
3  800.0      1800.0  640000.0        1440000.0     3240000.0
4  900.0      1600.0  810000.0        1440000.0     2560000.0
5  200.0      1000.0   40000.0         200000.0     1000000.0
6  120.0       900.0   14400.0         108000.0      810000.0
7  340.0      1100.0  115600.0         374000.0     1210000.0
8  490.0       900.0  240100.0         441000.0      810000.0
9  700.0       800.0  490000.0         560000.0      640000.0

In [9]:
poly = PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
X_poly_deg_3 = poly.fit_transform(X)
X_poly_deg_3

,Home,Automobile,Home^2,Home Automobile,Automobile^2,Home^3,Home^2 Automobile,Home Automobile^2,Automobile^3
0,400.0,1200.0,160000.0,480000.0,1440000.0,64000000.0,1.920000e+08,5.760000e+08,1.728000e+09
1,350.0,360.0,122500.0,126000.0,129600.0,42875000.0,4.410000e+07,4.536000e+07,4.665600e+07
2,600.0,800.0,360000.0,480000.0,640000.0,216000000.0,2.880000e+08,3.840000e+08,5.120000e+08
3,800.0,1800.0,640000.0,1440000.0,3240000.0,512000000.0,1.152000e+09,2.592000e+09,5.832000e+09
4,900.0,1600.0,810000.0,1440000.0,2560000.0,729000000.0,1.296000e+09,2.304000e+09,4.096000e+09
5,200.0,1000.0,40000.0,200000.0,1000000.0,8000000.0,4.000000e+07,2.000000e+08,1.000000e+09
6,120.0,900.0,14400.0,108000.0,810000.0,1728000.0,1.296000e+07,9.720000e+07,7.290000e+08
7,340.0,1100.0,115600.0,374000.0,1210000.0,39304000.0,1.271600e+08,4.114000e+08,1.331000e+09
8,490.0,900.0,240100.0,441000.0,810000.0,117649000.0,2.160900e+08,3.969000e+08,7.290000e+08
9,700.0,800.0,490000.0,560000.0,640000.0,343000000.0,3.920000e+08,4.480000e+08,5.120000e+08

In [10]:
boston = pd.read_csv("Boston.csv")
X = boston.drop('medv', axis = 1)
y = boston['medv']

poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform = 'pandas')
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size = 0.30, random_state = 26)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print("R2 = ", r2_score(y_test, y_pred))

R2 =  0.6657958510530829

### Housing Dataset

In [16]:
housing = pd.read_csv('Housing.csv')
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [17]:
dum_hous = pd.get_dummies(housing, dtype = int, drop_first  = True)
X, y = dum_hous.drop('price', axis = 1), dum_hous['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 26)

In [18]:
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print("R2 = ", r2_score(y_test, y_pred))

R2 =  0.6791781818067917

### with degree 2

In [19]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform = 'pandas')
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size = 0.3, random_state = 26)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print("R2 = ", r2_score(y_test, y_pred))

R2 =  0.4488658162013367

### with degree 3

In [20]:
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform = 'pandas')
X_poly = poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size = 0.3, random_state = 26)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print("R2 = ", r2_score(y_test, y_pred))

R2 =  -64.78637653467372