In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score
import warnings
from tqdm import tqdm
import os
os.chdir("/home/pgcp-ai/MachineLearning/Cases/Concrete_Strength/")

In [2]:
concrete = pd.read_csv("Concrete_Data.csv")
concrete

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [13]:
X, y = concrete.drop("Strength", axis = 1), concrete["Strength"]
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 26)

In [14]:
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [15]:
lr = LinearRegression()
dtr = DecisionTreeRegressor(random_state=26, max_depth=1)
el = ElasticNet()
knn = KNeighborsRegressor()
estimators = [lr, dtr, el,knn]
no_of_estimators = np.arange(1, 101)
scores = []

for e in tqdm(estimators):
    for n in no_of_estimators:
        ada = AdaBoostRegressor(n_estimators = n, random_state = 26, estimator = e)
        ada.fit(X_train, y_train)
        y_pred = ada.predict(X_test)
        scores.append([e, n, r2_score(y_test, y_pred)])
        
df_scores = pd.DataFrame(scores, columns = ["Estimator", "Number of Estimators", "R2 Score"])
df_scores.sort_values("R2 Score", ascending = False)

100%|█████████████████████████████████████████████| 4/4 [00:53<00:00, 13.32s/it]

,Estimator,Number of Estimators,R2 Score
333,KNeighborsRegressor(),34,0.727700
328,KNeighborsRegressor(),29,0.727213
334,KNeighborsRegressor(),35,0.727070
331,KNeighborsRegressor(),32,0.726741
327,KNeighborsRegressor(),28,0.726695
...,...,...,...
105,"DecisionTreeRegressor(max_depth=1, random_stat...",6,0.434945
104,"DecisionTreeRegressor(max_depth=1, random_stat...",5,0.431540
103,"DecisionTreeRegressor(max_depth=1, random_stat...",4,0.386169
101,"DecisionTreeRegressor(max_depth=1, random_stat...",2,0.212276
100,"DecisionTreeRegressor(max_depth=1, random_stat...",1,0.212276

In [12]:
!pip install XGBoost

Collecting XGBoost
  Downloading xgboost-2.1.4-py3-none-manylinux2014_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 476 kB/s eta 0:00:01
Requirement already satisfied: numpy in /home/pgcp-ai/.local/lib/python3.8/site-packages (from XGBoost) (1.24.4)
Requirement already satisfied: scipy in /home/pgcp-ai/.local/lib/python3.8/site-packages (from XGBoost) (1.10.1)
Installing collected packages: XGBoost
Successfully installed XGBoost-2.1.4