In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder
import os
os.chdir("C:/Users/PGCP-AI/ML/MachineLearning/Cases/Glass_Identification")

In [52]:
df = pd.read_csv("Glass.csv")
df

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,building_windows_float_processed
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,building_windows_float_processed
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,building_windows_float_processed
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,building_windows_float_processed
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,building_windows_float_processed
...,...,...,...,...,...,...,...,...,...,...
209,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,headlamps
210,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,headlamps
211,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0,headlamps
212,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0,headlamps
213,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.0,headlamps

In [53]:
le = LabelEncoder()
df["Type"] = le.fit_transform(df["Type"])

In [54]:
X,y = df.drop('Type',axis=1),df['Type']

In [44]:
# IF = IsolationForest(random_state=26,contamination=0.05)
IF = IsolationForest(random_state=26)
IF.fit(X)
pred_outliers = IF.predict(X)

In [45]:
pd.crosstab(colnames=['Outlier or Not'],rownames=['Type of Glass'],columns=pred_outliers,index=y,margins=True)

Outlier or Not                        -1    1  All
Type of Glass
building_windows_float_processed       0   70   70
building_windows_non_float_processed   8   68   76
containers                             5    8   13
headlamps                              8   21   29
tableware                              1    8    9
vehicle_windows_float_processed        1   16   17
All                                   23  191  214

In [47]:
print(f"Percentage of outliers: {(pred_outliers<0).mean():.6%}")

Percentage of outliers: 10.747664%

In [48]:
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV

In [57]:
in_glass = df[pred_outliers != -1]
kfold = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 26)
X,y = in_glass.drop('Type',axis=1),in_glass['Type']
params = {"learning_rate" : np.linspace(0.001, 0.9, 30), "n_estimators" : [10, 25, 50, 75, 100], "max_depth" : [2, 3, 4, 5, 6]}
gbm = XGBClassifier(random_state=26, n_jobs = -1)
gcv = GridSearchCV(gbm, param_grid = params, cv = kfold, scoring = 'neg_log_loss',verbose=3)
gcv.fit(X, y)

Fitting 5 folds for each of 750 candidates, totalling 3750 fits
[CV 1/5] END learning_rate=0.001, max_depth=2, n_estimators=10;, score=-1.446 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=2, n_estimators=10;, score=-1.423 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=2, n_estimators=10;, score=-1.423 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=2, n_estimators=10;, score=-1.464 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=2, n_estimators=10;, score=-1.478 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=2, n_estimators=25;, score=-1.437 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=2, n_estimators=25;, score=-1.410 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=2, n_estimators=25;, score=-1.410 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=2, n_estimators=25;, score=-1.454 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=2, n_estimators=25;, score=-1.464 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=2, n_estimators=50;, score=-1.422 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=2, n_estimators=50;, score=-1.390 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=2, n_estimators=50;, score=-1.390 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=2, n_estimators=50;, score=-1.438 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=2, n_estimators=50;, score=-1.444 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=2, n_estimators=75;, score=-1.407 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=2, n_estimators=75;, score=-1.371 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=2, n_estimators=75;, score=-1.369 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=2, n_estimators=75;, score=-1.422 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=2, n_estimators=75;, score=-1.425 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=2, n_estimators=100;, score=-1.393 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=2, n_estimators=100;, score=-1.353 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=2, n_estimators=100;, score=-1.350 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=2, n_estimators=100;, score=-1.408 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=2, n_estimators=100;, score=-1.407 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=3, n_estimators=10;, score=-1.445 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=3, n_estimators=10;, score=-1.422 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=3, n_estimators=10;, score=-1.421 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=3, n_estimators=10;, score=-1.463 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=3, n_estimators=10;, score=-1.478 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=3, n_estimators=25;, score=-1.435 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=3, n_estimators=25;, score=-1.409 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=3, n_estimators=25;, score=-1.407 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=3, n_estimators=25;, score=-1.451 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=3, n_estimators=25;, score=-1.464 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=3, n_estimators=50;, score=-1.419 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=3, n_estimators=50;, score=-1.387 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=3, n_estimators=50;, score=-1.383 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=3, n_estimators=50;, score=-1.432 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=3, n_estimators=50;, score=-1.442 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=3, n_estimators=75;, score=-1.403 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=3, n_estimators=75;, score=-1.367 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=3, n_estimators=75;, score=-1.361 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=3, n_estimators=75;, score=-1.415 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=3, n_estimators=75;, score=-1.423 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=3, n_estimators=100;, score=-1.388 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=3, n_estimators=100;, score=-1.348 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=3, n_estimators=100;, score=-1.339 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=3, n_estimators=100;, score=-1.398 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=3, n_estimators=100;, score=-1.405 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=4, n_estimators=10;, score=-1.445 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=4, n_estimators=10;, score=-1.422 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=4, n_estimators=10;, score=-1.420 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=4, n_estimators=10;, score=-1.463 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=4, n_estimators=10;, score=-1.477 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=4, n_estimators=25;, score=-1.435 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=4, n_estimators=25;, score=-1.408 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=4, n_estimators=25;, score=-1.404 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=4, n_estimators=25;, score=-1.450 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=4, n_estimators=25;, score=-1.462 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=4, n_estimators=50;, score=-1.419 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=4, n_estimators=50;, score=-1.384 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=4, n_estimators=50;, score=-1.379 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=4, n_estimators=50;, score=-1.431 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=4, n_estimators=50;, score=-1.440 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=4, n_estimators=75;, score=-1.403 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=4, n_estimators=75;, score=-1.363 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=4, n_estimators=75;, score=-1.354 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=4, n_estimators=75;, score=-1.412 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=4, n_estimators=75;, score=-1.419 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=4, n_estimators=100;, score=-1.388 total time=   0.1s
[CV 2/5] END learning_rate=0.001, max_depth=4, n_estimators=100;, score=-1.343 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=4, n_estimators=100;, score=-1.330 total time=   0.1s
[CV 4/5] END learning_rate=0.001, max_depth=4, n_estimators=100;, score=-1.395 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=4, n_estimators=100;, score=-1.398 total time=   0.1s
[CV 1/5] END learning_rate=0.001, max_depth=5, n_estimators=10;, score=-1.445 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=5, n_estimators=10;, score=-1.422 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=5, n_estimators=10;, score=-1.420 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=5, n_estimators=10;, score=-1.462 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=5, n_estimators=10;, score=-1.477 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=5, n_estimators=25;, score=-1.434 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=5, n_estimators=25;, score=-1.407 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=5, n_estimators=25;, score=-1.404 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=5, n_estimators=25;, score=-1.449 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=5, n_estimators=25;, score=-1.462 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=5, n_estimators=50;, score=-1.417 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=5, n_estimators=50;, score=-1.383 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=5, n_estimators=50;, score=-1.377 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=5, n_estimators=50;, score=-1.428 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=5, n_estimators=50;, score=-1.439 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=5, n_estimators=75;, score=-1.400 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=5, n_estimators=75;, score=-1.361 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=5, n_estimators=75;, score=-1.351 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=5, n_estimators=75;, score=-1.409 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=5, n_estimators=75;, score=-1.419 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=5, n_estimators=100;, score=-1.384 total time=   0.1s
[CV 2/5] END learning_rate=0.001, max_depth=5, n_estimators=100;, score=-1.341 total time=   0.1s
[CV 3/5] END learning_rate=0.001, max_depth=5, n_estimators=100;, score=-1.327 total time=   0.1s
[CV 4/5] END learning_rate=0.001, max_depth=5, n_estimators=100;, score=-1.390 total time=   0.1s
[CV 5/5] END learning_rate=0.001, max_depth=5, n_estimators=100;, score=-1.399 total time=   0.1s
[CV 1/5] END learning_rate=0.001, max_depth=6, n_estimators=10;, score=-1.444 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=6, n_estimators=10;, score=-1.421 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=6, n_estimators=10;, score=-1.420 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=6, n_estimators=10;, score=-1.462 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=6, n_estimators=10;, score=-1.477 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=6, n_estimators=25;, score=-1.433 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=6, n_estimators=25;, score=-1.407 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=6, n_estimators=25;, score=-1.403 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=6, n_estimators=25;, score=-1.449 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=6, n_estimators=25;, score=-1.462 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=6, n_estimators=50;, score=-1.414 total time=   0.0s
[CV 2/5] END learning_rate=0.001, max_depth=6, n_estimators=50;, score=-1.383 total time=   0.0s
[CV 3/5] END learning_rate=0.001, max_depth=6, n_estimators=50;, score=-1.376 total time=   0.0s
[CV 4/5] END learning_rate=0.001, max_depth=6, n_estimators=50;, score=-1.427 total time=   0.0s
[CV 5/5] END learning_rate=0.001, max_depth=6, n_estimators=50;, score=-1.439 total time=   0.0s
[CV 1/5] END learning_rate=0.001, max_depth=6, n_estimators=75;, score=-1.396 total time=   0.1s
[CV 2/5] END learning_rate=0.001, max_depth=6, n_estimators=75;, score=-1.360 total time=   0.1s
[CV 3/5] END learning_rate=0.001, max_depth=6, n_estimators=75;, score=-1.351 total time=   0.1s
[CV 4/5] END learning_rate=0.001, max_depth=6, n_estimators=75;, score=-1.407 total time=   0.1s
[CV 5/5] END learning_rate=0.001, max_depth=6, n_estimators=75;, score=-1.417 total time=   0.1s
[CV 1/5] END learning_rate=0.001, max_depth=6, n_estimators=100;, score=-1.379 total time=   0.2s
[CV 2/5] END learning_rate=0.001, max_depth=6, n_estimators=100;, score=-1.340 total time=   0.1s
[CV 3/5] END learning_rate=0.001, max_depth=6, n_estimators=100;, score=-1.326 total time=   0.1s
[CV 4/5] END learning_rate=0.001, max_depth=6, n_estimators=100;, score=-1.388 total time=   0.1s
[CV 5/5] END learning_rate=0.001, max_depth=6, n_estimators=100;, score=-1.397 total time=   0.1s
[CV 1/5] END learning_rate=0.032, max_depth=2, n_estimators=10;, score=-1.283 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=2, n_estimators=10;, score=-1.220 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=2, n_estimators=10;, score=-1.186 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=2, n_estimators=10;, score=-1.305 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=2, n_estimators=10;, score=-1.262 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=2, n_estimators=25;, score=-1.130 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=2, n_estimators=25;, score=-1.048 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=2, n_estimators=25;, score=-0.972 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=2, n_estimators=25;, score=-1.168 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=2, n_estimators=25;, score=-1.078 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=2, n_estimators=50;, score=-1.012 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=2, n_estimators=50;, score=-0.886 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=2, n_estimators=50;, score=-0.790 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=2, n_estimators=50;, score=-1.059 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=2, n_estimators=50;, score=-0.929 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=2, n_estimators=75;, score=-0.905 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=2, n_estimators=75;, score=-0.789 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=2, n_estimators=75;, score=-0.670 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=2, n_estimators=75;, score=-1.013 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=2, n_estimators=75;, score=-0.852 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=2, n_estimators=100;, score=-0.854 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=2, n_estimators=100;, score=-0.734 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=2, n_estimators=100;, score=-0.595 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=2, n_estimators=100;, score=-0.996 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=2, n_estimators=100;, score=-0.795 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=3, n_estimators=10;, score=-1.273 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=3, n_estimators=10;, score=-1.207 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=3, n_estimators=10;, score=-1.172 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=3, n_estimators=10;, score=-1.279 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=3, n_estimators=10;, score=-1.256 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=3, n_estimators=25;, score=-1.120 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=3, n_estimators=25;, score=-1.025 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=3, n_estimators=25;, score=-0.916 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=3, n_estimators=25;, score=-1.141 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=3, n_estimators=25;, score=-1.065 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=3, n_estimators=50;, score=-0.986 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=3, n_estimators=50;, score=-0.818 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=3, n_estimators=50;, score=-0.707 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=3, n_estimators=50;, score=-1.040 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=3, n_estimators=50;, score=-0.906 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=3, n_estimators=75;, score=-0.897 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=3, n_estimators=75;, score=-0.710 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=3, n_estimators=75;, score=-0.593 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=3, n_estimators=75;, score=-0.982 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=3, n_estimators=75;, score=-0.788 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=3, n_estimators=100;, score=-0.857 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=3, n_estimators=100;, score=-0.650 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=3, n_estimators=100;, score=-0.525 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=3, n_estimators=100;, score=-0.981 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=3, n_estimators=100;, score=-0.724 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=4, n_estimators=10;, score=-1.276 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=4, n_estimators=10;, score=-1.190 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=4, n_estimators=10;, score=-1.145 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=4, n_estimators=10;, score=-1.272 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=4, n_estimators=10;, score=-1.233 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=4, n_estimators=25;, score=-1.127 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=4, n_estimators=25;, score=-0.990 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=4, n_estimators=25;, score=-0.890 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=4, n_estimators=25;, score=-1.133 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=4, n_estimators=25;, score=-1.026 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=4, n_estimators=50;, score=-0.991 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=4, n_estimators=50;, score=-0.794 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=4, n_estimators=50;, score=-0.671 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=4, n_estimators=50;, score=-1.061 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=4, n_estimators=50;, score=-0.846 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=4, n_estimators=75;, score=-0.912 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=4, n_estimators=75;, score=-0.676 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=4, n_estimators=75;, score=-0.561 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=4, n_estimators=75;, score=-1.003 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=4, n_estimators=75;, score=-0.786 total time=   0.0s
[CV 1/5] END learning_rate=0.032, max_depth=4, n_estimators=100;, score=-0.870 total time=   0.1s
[CV 2/5] END learning_rate=0.032, max_depth=4, n_estimators=100;, score=-0.614 total time=   0.1s
[CV 3/5] END learning_rate=0.032, max_depth=4, n_estimators=100;, score=-0.488 total time=   0.1s
[CV 4/5] END learning_rate=0.032, max_depth=4, n_estimators=100;, score=-0.974 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=4, n_estimators=100;, score=-0.767 total time=   0.1s
[CV 1/5] END learning_rate=0.032, max_depth=5, n_estimators=10;, score=-1.265 total time=   0.0s
[CV 2/5] END learning_rate=0.032, max_depth=5, n_estimators=10;, score=-1.186 total time=   0.0s
[CV 3/5] END learning_rate=0.032, max_depth=5, n_estimators=10;, score=-1.138 total time=   0.0s
[CV 4/5] END learning_rate=0.032, max_depth=5, n_estimators=10;, score=-1.260 total time=   0.0s
[CV 5/5] END learning_rate=0.032, max_depth=5, n_estimators=10;, score=-1.234 total time=   0.0s

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=26, shuffle=True),
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=None, grow_polic...
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=-1, num_parallel_tree=None, ...),
             param_grid={'learning_rate': array([0.001, 0.032, 0.063, 0.094, 0.125, 0.156, 0.187, 0.218, 0.249,
       0.28 , 0.311, 0.342, 0.373, 0.404, 0.435, 0.466, 0.497, 0.528,
       0.559, 0.59 , 0.621, 0.652, 0.683, 0.714, 0.745, 0.776, 0.807,
       0.838, 0.869, 0.9  ]),
                         'max_depth': [2, 3, 4, 5, 6],
                         'n_estimators': [10, 25, 50, 75, 100]},
             scoring='neg_log_loss', verbose=3)

In [59]:
gcv.best_params_, gcv.best_score_

({'learning_rate': np.float64(0.6829999999999999),
  'max_depth': 6,
  'n_estimators': 10},
 np.float64(-0.6708996359025863))